### ISSUE TITLE
Unable to run more than one word commands properly

### ISSUE THREAD

**Issue by MiguelGoncalves98** [lalilaloe/wttab#2]
First of all, I am sorry if this is me being unable to grasp something basic about the functionality of "wttab".

Essentially, I had a script in my "package.json file" to do the following bit of code.

![image](https://user-images.githubusercontent.com/47758199/116744629-78df1e00-a9f2-11eb-87b5-9d3cff984a9a.png)

The first script ("tab:launch:bot1") that used only the "ls" command worked fine, however, the second ("tab:launch:bot2") that ran a command separated by spaces was getting messed up, as the Powershell was separating them commas. I tried to escape the spaces, to put the command between (') and none of it seemed to work. Once again, I am sorry if this is me being unable to grasp anything obvious.

I ended up adding a little bit of a hacky solution (seen below, highlighted), that essentially checks if the command has content separated by spaces and interprets it as a single, joint command.
![image](https://user-images.githubusercontent.com/47758199/116745677-5568a300-a9f3-11eb-9846-8b2bf92564a0.png)

I'm sure this is not the way to do it, and it may even cause problems for other cases, I just found a way to fix it for what I wanted.

Anyways, I would like to know if this had a simpler and more elegant solution, if it was something I missed, or if there was another way to workaround it.

Thanks in advance!

**Comment by lalilaloe** [comment]
This is a known bug, in the mean time you can use quotes to get arround this ex. ```wttab -t Bot2 'npm run launch:bot2'```. It would be nice to add support for quotless commands while passing other parameters.

**Comment by MiguelGoncalves98** [comment]
I tried doing so, and intended to say I did it, but maybe the message was poorly phrased. When I tried to put the quotes, the Powershell interpreted it as 3 seperate commands, essentially it ran 'npm' first, then 'run', and then 'launch:bot2'! That, of course, yielded some errors :(

**Comment by lalilaloe** [comment]
What terminal do you try to launch?

**Comment by MiguelGoncalves98** [comment]
I ran it on windows terminal, which was using Powershell.

**Comment by lalilaloe** [comment]
This is now fixed in [v1.1.0](610b1a35a37d52735ce6febd783438c620901620) see 77eccaecb9b962aa1171804667a46e96cbcd2f83

Powershell executed it as an array instead of a string
